services:
  fastapi:
    build: ./BE
    ports:
      - "8000:8000"
    volumes:
      - ./BE:/app
    depends_on:
      - mysql-db
      - elasticsearch

  mysql-db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - ./BE/env/db.env
    ports:
      - 3307:3306

  elasticsearch:
    image: elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  
  # npm-tool:
  #   image: node:21-alpine
  #   volumes:
  #     - ./FE:/app
  #   stdin_open: true
  #   tty: true

  vuejs:
    build: ./FE
    ports:
      - "8080:5173"
    tty: true
    stdin_open: true
    volumes:
      - ./FE:/app
      - /app/node_modules
    depends_on:
      - fastapi

volumes:
  db-data:
  es-data:
